{% set version = "1.0.7" %}
{% set python_min = "3.10" %}

package:
  name: ultraplot
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/ultraplot/ultraplot-{{ version }}.tar.gz
  sha256: f14d35f81fdab4157e2b659f952fa6045bb40e1a824b43b2842f1b0c2b62248a

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - importlib-metadata
    - python >={{ python_min }}
    - matplotlib-base >=3.9.2

test:
  imports:
    - ultraplot
  commands:
    # - pip check  # fails due to basemap not on mpl10
    - python -c "import ultraplot; assert ultraplot.__version__ == '{{ version }}'.replace('v', '')"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ultraplot/ultraplot
  license: MIT
  license_file: LICENSE.txt
  summary: Elegant and flexible high-level plotting with matplotlib
  description: |
    Ultraplot is a Python library that provides a high-level interface for creating
    publication-quality plots using matplotlib. It focuses on making common plotting
    tasks simple while maintaining full flexibility for customization.
  dev_url: https://github.com/ultraplot/ultraplot/issues

extra:
  recipe-maintainers:
    - cvanelteren
    - beckermr
