context:
  version: "2.7.0"
  mpl_min: "3.9"
  mpl_max: "3.12"

package:
  name: ultraplot
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/u/ultraplot/ultraplot-${{ version }}.tar.gz
  sha256: c697ad6b64dc75f6b9fbeff593228c40ccf78a1bc5bb70fd2c5abdc8df227af5

build:
  number: 0
  noarch: python
  script:
    content: pip install . -vv
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
  python:
    entry_points:
      - ultraplot-mcp = ultraplot.mcp:main
  files:
    exclude:
      - var/cache/fontconfig/*
      - "**/site-packages/ultraplot/tests/**"
      - "**/site-packages/tools/**"

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm
    - matplotlib-base >=${{ mpl_min }},<${{ mpl_max }}
  run:
    - python >=${{ python_min }}
    - numpy >=1.26.0
    - matplotlib-base >=${{ mpl_min }},<${{ mpl_max }}
    - typing-extensions

tests:
  - python:
      imports:
        - ultraplot
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      content: pytest -q --tb=short --disable-warnings ultraplot/tests
    files:
      source:
        - pyproject.toml
        - ultraplot/tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
        - pytest-mpl
        - cartopy
        - cftime
        - pandas
        - pint
        - pyarrow
        - pyyaml
        - seaborn
        - xarray

about:
  homepage: https://ultraplot.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Elegant and flexible high-level plotting with matplotlib
  description: |
    Ultraplot is a Python library that provides a high-level interface for creating
    publication-quality plots using matplotlib. It focuses on making common plotting
    tasks simple while maintaining full flexibility for customization.
  repository: https://github.com/ultraplot/ultraplot
  documentation: https://ultraplot.readthedocs.io/

extra:
  recipe-maintainers:
    - cvanelteren
    - beckermr
    - munechika-koyo
