schema_version: 1

context:
  version: "2.7.0"
  python_min: "3.10"

package:
  name: ultraplot
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/u/ultraplot/ultraplot-${{ version }}.tar.gz
  sha256: c697ad6b64dc75f6b9fbeff593228c40ccf78a1bc5bb70fd2c5abdc8df227af5

build:
  number: 1
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm
    - numpy >=1.26.0
    - matplotlib-base >=3.9, <3.12
  run:
    - importlib-metadata
    - python >=${{ python_min }}
    - matplotlib-base >=3.9,<3.12
    - numpy >=1.26.0
    - typing-extensions
  run_constraints:
    - basemap >=1.4.1

tests:
  - python:
      imports:
        - ultraplot
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - python -c "import ultraplot; assert ultraplot.__version__ == '${{ version }}'.replace('v', '')"

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Elegant and flexible high-level plotting with matplotlib
  description: |
    Ultraplot is a Python library that provides a high-level interface for creating
    publication-quality plots using matplotlib. It focuses on making common plotting
    tasks simple while maintaining full flexibility for customization.
  homepage: https://github.com/ultraplot/ultraplot
  repository: https://github.com/ultraplot/ultraplot/issues

extra:
  recipe-maintainers:
    - cvanelteren
    - beckermr
