schema_version: 1

context:
  version: "2.7.2"
  mpl_min: "3.9"
  mpl_max: "3.12"

package:
  name: ultraplot
  version: ${{ version }}

source:
  url: https://github.com/ultraplot/ultraplot/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 921fa85beca65a8e0d7232620c7e3cd3ee79c1feb4d50920742df028dfd4c8e5
  patches:
    - package-data.patch

build:
  number: 1
  noarch: python
  script:
    content: pip install . -vv
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
  python:
    entry_points:
      - ultraplot-mcp = ultraplot.mcp:main
  files:
    exclude:
      - var/cache/fontconfig/*
      - "**/site-packages/ultraplot/tests/**"
      - "**/site-packages/tools/**"

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm
    - numpy >=1.26.0
    - matplotlib-base >=${{ mpl_min }},<${{ mpl_max }}
  run:
    - python >=${{ python_min }}
    - numpy >=1.26.0
    - matplotlib-base >=${{ mpl_min }},<${{ mpl_max }}
    - typing-extensions

tests:
  - python:
      imports:
        - ultraplot
      python_version:
        - ${{ python_min }}.*
        - "*"

  - script:
      interpreter: python
      content: |
        import ultraplot as uplt

        assert uplt.__version__ == '${{ version }}'

        fig, ax = uplt.subplots()
        ax.plot([0, 1], [0, 1])

  - script:
      content:
        - ultraplot-mcp --help
    requirements:
      run:
        - python ${{ python_min }}.*
        - matplotlib-base ${{ mpl_min }}.*
        - mcp >=2.1,<3

  - package_contents:
      files:
        - "**/site-packages/ultraplot/fonts/**.ttf"
        - "**/site-packages/ultraplot/cmaps/**.rgb"
        - "**/site-packages/ultraplot/cycles/**.hex"

about:
  homepage: https://ultraplot.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Elegant and flexible high-level plotting with matplotlib
  description: |
    Ultraplot is a Python library that provides a high-level interface for creating
    publication-quality plots using matplotlib. It focuses on making common plotting
    tasks simple while maintaining full flexibility for customization.
  repository: https://github.com/ultraplot/ultraplot
  documentation: https://ultraplot.readthedocs.io/

extra:
  recipe-maintainers:
    - cvanelteren
    - beckermr
    - munechika-koyo
